In [5]:
import numpy as np
from PIL import Image
import os



data_root = '../data'
image_root = data_root + '/CephalometricLandmark/RawImage'
txt_root = data_root + '/CephalometricLandmark/AnnotationsByMD'

cropped_root = data_root + '/CephalometricLandmark/CroppedImage'
if not os.path.exists(cropped_root):
    os.mkdir(cropped_root)
    
for i in range(19):
    if not os.path.exists(cropped_root + "/%02d" % (i + 1)):
        os.mkdir(cropped_root + "/%02d" % (i + 1))

x = [[] for i in range(19)]
y = [[] for i in range(19)]
width = 640
height = 640

for i in range(1, 151):
    txt_filename1 = txt_root + '/400_senior' + "/%03d.txt" % i
    # txt_filename1 = './400_senior' + "/%03d.txt" % i

    with open(txt_filename1, 'r') as f:
        txts = f.read().split()
    for j in range(19):
        x[j].append(int(txts[j].split(',')[0]))
        y[j].append(int(txts[j].split(',')[1]))
for j in range(19):
    minx = np.min(x[j])
    miny = np.min(y[j])
    maxx = np.max(x[j])
    maxy = np.max(y[j])

    print(maxx - minx, maxy - miny)

    x0 = int(minx - (width - (maxx - minx)) / 2)
    x1 = int(maxx + (width - (maxx - minx)) / 2)

    y0 = int(miny - (height - (maxy - miny)) / 2)
    y1 = int(maxy + (height - (maxy - miny)) / 2)

    print(x0, y0)
    print(x1, y1)

    for index in range(1, 151):
        image_path = image_root + '/TrainingData'
        image_filename = image_path + "/%03d.bmp" % index
        im = Image.open(image_filename)
        region = im.crop((x0, y0, x1, y1))
        region.save(cropped_root + "/%02d/%03d.bmp" % (j + 1, index))

    for index in range(151, 301):
        image_path = image_root + '/Test1Data'
        image_filename = image_path + "/%03d.bmp" % index
        im = Image.open(image_filename)
        region = im.crop((x0, y0, x1, y1))
        region.save(cropped_root + "/%02d/%03d.bmp" % (j + 1, index))

    for index in range(301, 401):
        image_path = image_root + '/Test2Data'
        image_filename = image_path + "/%03d.bmp" % index
        im = Image.open(image_filename)
        region = im.crop((x0, y0, x1, y1))
        region.save(cropped_root + "/%02d/%03d.bmp" % (j + 1, index))


238 263
504 697
1144 1337
331 388
1063 606
1703 1246
239 353
948 888
1588 1528
185 173
286 902
926 1542
316 366
1079 1191
1719 1831
450 383
1053 1507
1693 2147
504 437
1048 1661
1688 2301
535 446
993 1729
1633 2369
518 451
1025 1706
1665 2346
318 448
415 1391
1055 2031
372 390
1121 1355
1761 1995
378 398
1138 1388
1778 2028
354 444
1245 1294
1885 1934
429 436
1212 1477
1852 2117
342 422
1170 1152
1810 1792
518 468
1114 1756
1754 2396
247 263
635 1090
1275 1730
293 379
1081 1100
1721 1740
198 229
350 1006
990 1646


<class 'mxnet.ndarray.ndarray.NDArray'>
<class 'mxnet.ndarray.ndarray.NDArray'>


([
  [[[223 223 223]
    [221 221 221]
    [217 217 217]
    ..., 
    [156 156 156]
    [168 168 168]
    [163 163 163]]
  
   [[221 221 221]
    [221 221 221]
    [219 219 219]
    ..., 
    [159 159 159]
    [168 168 168]
    [165 165 165]]
  
   [[218 218 218]
    [220 220 220]
    [219 219 219]
    ..., 
    [161 161 161]
    [166 166 166]
    [165 165 165]]
  
   ..., 
   [[223 223 223]
    [222 222 222]
    [220 220 220]
    ..., 
    [ 51  51  51]
    [ 49  49  49]
    [ 48  48  48]]
  
   [[221 221 221]
    [221 221 221]
    [224 224 224]
    ..., 
    [ 49  49  49]
    [ 47  47  47]
    [ 45  45  45]]
  
   [[220 220 220]
    [219 219 219]
    [217 217 217]
    ..., 
    [ 44  44  44]
    [ 41  41  41]
    [ 41  41  41]]]
  <NDArray 640x640x3 @cpu(0)>], [
  [[ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   ..., 
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]]
  <NDArray